<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/lofcz/LlmTornado</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lofcz/LlmTornado</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
    <Description>Enable seamless, standardized communication between AI agents and client applications via the Agent Client Protocol (ACP).</Description>
    <PackageTags>acp;agent-client-protocol;sdk;agent;workflow;orchestration;json-rpc;agents;agentic</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlmTornado.Agents\LlmTornado.Agents.csproj" />
    <ProjectReference Include="..\LlmTornado\LlmTornado.csproj" />
  </ItemGroup>

</Project>
