import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { dirname, extname, join, relative, resolve, sep } from 'node:path'

const websiteRoot = resolve(import.meta.dirname, '..')
const docsRoot = join(websiteRoot, 'docs')

function walk(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    if (entry.name.startsWith('.')) return []
    const path = join(directory, entry.name)
    return entry.isDirectory() ? walk(path) : [path]
  })
}

function rewriteRoute(id) {
  return ('/' + id.replaceAll(sep, '/'))
    .replace(/\/(\d+)\.\s+/g, '/')
    .replace(/^\/(\d+)\.\s+/, '/')
    .replace(/\.md$/i, '')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/\/index$/, '/')
}

const markdownFiles = walk(docsRoot).filter(path => extname(path).toLowerCase() === '.md')
const routes = new Set(markdownFiles.map(path => rewriteRoute(relative(docsRoot, path))))
routes.add('/')
routes.add('/playground/') // generated by the Blazor documentation build

const errors = []
const forbidden = [
  ['agent.RunAsync(', 'use the current TornadoAgent.Run method'],
  ['ChatModel.OpenAi.Gpt35Turbo', 'use a current model constant'],
  ['ChatModel.OpenAi.Gpt4.Turbo', 'use a current model constant'],
  ['Gemini2Flash001', 'use a current model constant'],
  ['LlmTornado.Cli', 'the CLI is not part of the shipped documentation surface'],
  ['/tools allow-all', 'the CLI is not part of the shipped documentation surface']
]
const trustBaselineFiles = new Set([
  'docs/getting-started.md',
  'docs/1. LlmTornado/Responses/1. Overview.md',
  'docs/2. Agents/1. Getting-Started.md',
  'docs/2. Agents/2. Tornado-Agent/5. Persistent-Conversation.md',
  'docs/2. Agents/2. Tornado-Agent/7. Tornado-Runner.md',
  'docs/8. Advanced and Preview/1. Custom-Providers.md',
  'docs/8. Advanced and Preview/2. Codex-Routing.md'
])

function report(file, line, message) {
  errors.push(`${relative(websiteRoot, file)}:${line}: ${message}`)
}

function validateTarget(file, lineNumber, rawTarget) {
  const target = rawTarget.trim().replace(/^<|>$/g, '').split(/\s+["']/)[0]
  if (!target || /^(https?:|mailto:|tel:|data:|#)/i.test(target)) return

  const withoutFragment = target.split('#')[0].split('?')[0]
  if (!withoutFragment) return

  let decoded
  try {
    decoded = decodeURIComponent(withoutFragment)
  } catch {
    report(file, lineNumber, `invalid URL encoding in local link: ${target}`)
    return
  }

  if (decoded.startsWith('/')) {
    const normalized = decoded.length > 1 ? decoded.replace(/\/$/, '') : decoded
    if (routes.has(decoded) || routes.has(normalized) || existsSync(join(docsRoot, decoded.slice(1)))) return
    report(file, lineNumber, `dead local route: ${target}`)
    return
  }

  const physical = resolve(dirname(file), decoded)
  if (existsSync(physical)) return

  const routeBase = dirname(rewriteRoute(relative(docsRoot, file))).replaceAll('\\', '/')
  const routeCandidate = resolve('/', routeBase, decoded).replaceAll('\\', '/')
    .replace(/\.md$/i, '').replace(/\/$/, '')
  if (routes.has(routeCandidate)) return

  report(file, lineNumber, `dead local link: ${target}`)
}

for (const file of markdownFiles) {
  const content = readFileSync(file, 'utf8')
  const lines = content.split(/\r?\n/)
  let fence = null
  let fenceStart = 0
  let fenceHasContent = false

  for (let index = 0; index < lines.length; index++) {
    const line = lines[index]
    const fenceMatch = line.match(/^\s*(```+|~~~+)\s*([^\s]*)/)
    if (fenceMatch) {
      if (!fence) {
        fence = { marker: fenceMatch[1][0], language: fenceMatch[2].toLowerCase() }
        fenceStart = index + 1
        fenceHasContent = false
      } else if (fence.marker === fenceMatch[1][0]) {
        if (['csharp', 'cs'].includes(fence.language) && !fenceHasContent) {
          report(file, fenceStart, 'empty C# snippet')
        }
        fence = null
      }
      continue
    }

    if (fence) {
      if (line.trim()) fenceHasContent = true
      continue
    }

    const targets = [
      ...line.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g),
      ...line.matchAll(/\b(?:href|src)=["']([^"']+)["']/g)
    ]
    for (const match of targets) validateTarget(file, index + 1, match[1])
  }

  if (fence) report(file, fenceStart, `unclosed ${fence.marker.repeat(3)} fence`)

  if (!trustBaselineFiles.has(relative(websiteRoot, file).replaceAll('\\', '/'))) continue

  for (const [pattern, guidance] of forbidden) {
    const position = content.indexOf(pattern)
    if (position >= 0) {
      const line = content.slice(0, position).split(/\r?\n/).length
      report(file, line, `stale or out-of-scope snippet (${pattern}); ${guidance}`)
    }
  }
}

if (errors.length) {
  console.error(`Documentation validation failed with ${errors.length} issue(s):`)
  for (const error of errors) console.error(`- ${error}`)
  process.exit(1)
}

console.log(`Documentation validation passed (${markdownFiles.length} Markdown files, ${routes.size} routes).`)
