namespace LlmTornado.Images.Vendors.Google;

/// <summary>
/// Extensions to image generation request for Google.
/// </summary>
public class ImageGenerationRequestGoogleExtensions
{
    /// <summary>
    /// The Cloud Storage bucket to store the output images. If not provided, base64-encoded image bytes are returned in the response. Sample value: gs://image-bucket/output/
    /// </summary>
    public string? StorageUri { get; set; }
    
    /// <summary>
    /// A parameter to use an LLM-based prompt rewriting feature to deliver higher quality images that better reflect the original prompt's intent. Disabling this feature may impact image quality and prompt adherence. Default value: true.
    /// </summary>
    public bool? EnablePromptRewriting { get; set; }
    
    /// <summary>
    /// Only applies to JPEG output files. The level of detail the model preserves for images generated in JPEG file format. Values: 0 to 100, where a higher number means more compression. Default: 75.
    /// </summary>
    public int? CompressionQuality { get; set; }
    
    /// <summary>
    /// The safety setting that controls the type of people or face generation the model allows.
    /// </summary>
    public ImageGenerationRequestGoogleExtensionsPersonSettings? PersonSetting { get; set; }
    
    /// <summary>
    /// The MIME type of the content of the image.
    /// </summary>
    public ImageGenerationRequestGoogleExtensionsMimeTypes? MimeType { get; set; }
    
    /// <summary>
    /// A setting that controls safety filter thresholds for generated images.
    /// </summary>
    public ImageGenerationRequestGoogleExtensionsSafetySettings? SafetySetting { get; set; }
}

/// <summary>
/// The safety setting that controls the type of people or face generation the model allows. 
/// </summary>
public enum ImageGenerationRequestGoogleExtensionsSafetySettings
{
    /// <summary>
    /// The highest safety threshold, resulting in the largest amount of generated images that are filtered. Previous value: block_most.
    /// </summary>
    BlockLowAndAbove,
    
    /// <summary>
    /// block_medium_and_above: A medium safety threshold that balances filtering for potentially harmful and safe content. Previous value: block_some.
    /// </summary>
    BlockMediumAndAbove,
    
    /// <summary>
    /// A safety threshold that reduces the number of requests blocked due to safety filters. This setting might increase objectionable content generated by Imagen. Previous value: block_few.
    /// </summary>
    BlockOnlyHigh
}

/// <summary>
/// The safety setting that controls the type of people or face generation the model allows.
/// </summary>
public enum ImageGenerationRequestGoogleExtensionsPersonSettings
{
    /// <summary>
    /// Allow generation of adults only, except for celebrity generation. Celebrity generation is not allowed for any setting.
    /// </summary>
    AllowAdult,
    
    /// <summary>
    /// Disable the inclusion of people or faces in generated images.
    /// </summary>
    DontAllow
}

/// <summary>
/// The MIME type of the content of the image.
/// </summary>
public enum ImageGenerationRequestGoogleExtensionsMimeTypes
{
    /// <summary>
    /// image/jpeg
    /// </summary>
    Jpeg,
    
    /// <summary>
    /// image/gif
    /// </summary>
    Gif,
    
    /// <summary>
    /// image/png
    /// </summary>
    Png,
    
    /// <summary>
    /// image/webp
    /// </summary>
    Webp,
    
    /// <summary>
    /// image/bmp
    /// </summary>
    Bmp,
    
    /// <summary>
    /// image/tiff
    /// </summary>
    Tiff,
    
    /// <summary>
    /// image/vnd.microsoft.icon
    /// </summary>
    Icon
}