using Newtonsoft.Json;

namespace LlmTornado.Threads
{
    /// <summary>
    /// Base class representing an annotation in a message with information about
    /// the text to be replaced and the position where it occurs.
    /// </summary>
    public abstract class MessageAnnotation
    {
        /// <summary>
        /// The type of annotation. For example: "file_citation", "file_path", etc.
        /// </summary>
        [JsonProperty("type")]
        public required string Type { get; set; }

        /// <summary>
        /// The text in the message content that needs to be replaced.
        /// </summary>
        [JsonProperty("text")]
        public string? Text { get; set; }

        /// <summary>
        /// The start index of the text to be replaced.
        /// </summary>
        [JsonProperty("start_index")]
        public int StartIndex { get; private set; }

        /// <summary>
        /// The end index of the text to be replaced.
        /// </summary>
        [JsonProperty("end_index")]
        public int EndIndex { get; private set; }
    }

    /// <summary>
    /// A citation within the message that points to a specific quote
    /// from a specific File associated with the assistant or the message.
    /// Generated when the assistant uses the "file_search" tool to search files. 
    /// </summary>
    public sealed class MessageAnnotationFileCitation : MessageAnnotation
    {
        /// <summary>
        /// Initializes a new instance of <see cref="MessageAnnotationFileCitation"/> 
        /// with the type set to "file_citation".
        /// </summary>
        public MessageAnnotationFileCitation()
        {
            Type = "file_citation";
        }

        /// <summary>
        /// The ID of the specific file the citation is from.
        /// </summary>
        [JsonProperty("file_citation")]
        public FileCitationData? FileCitationData { get; set; }
    }

    /// <summary>
    /// Represents a URL (file path) for the file generated by a tool (for example, code interpreter).
    /// </summary>
    public sealed class MessageAnnotationFilePath : MessageAnnotation
    {
        /// <summary>
        /// Initializes a new instance of <see cref="MessageAnnotationFilePath"/> 
        /// with the type set to "file_path".
        /// </summary>
        public MessageAnnotationFilePath()
        {
            Type = "file_path";
        }

        /// <summary>
        /// The ID of the file that was generated.
        /// </summary>
        [JsonProperty("file_path")]
        public FilePathData? FilePath { get; set; }
    }


    /// <summary>
    ///     Data related to FilePath annotation
    /// </summary>
    public sealed class FilePathData
    {
        /// <summary>
        ///     The ID of the file that was generated.
        /// </summary>
        [JsonProperty("file_id")]
        public string FileId { get; set; } = null!;
    }
    
    /// <summary>
    ///     Data related to FileCitation annotation
    /// </summary>
    public sealed class FileCitationData
    {
        /// <summary>
        ///     The ID of the specific File the citation is from.
        /// </summary>
        [JsonProperty("file_id")]
        public string FileId { get; set; } = null!;
    }
}