namespace LlmTornado.Agents
{
    /// <summary>
    /// Converted Response from the providers model
    /// </summary>
    public class ModelResponse
    {
        /// <summary>
        /// Id of the response API response (Doesn't work with Chat API)
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Json Format of the response Result
        /// </summary>
        public ModelOutputFormat? OutputFormat { get; set; }

        /// <summary>
        /// Model being used (Unused here)
        /// </summary>
        public string? Model { get; set; }

        /// <summary>
        /// Message History 
        /// </summary>
        public List<ModelItem> Messages { get; set; } = new List<ModelItem>();

        /// <summary>
        /// Items Generated by the last response
        /// </summary>
        public List<ModelItem>? OutputItems { get; set; }

        public ModelResponse() { }

        public ModelResponse(List<ModelItem> outputItems = null, ModelOutputFormat outputFormat = null, List<ModelItem> messages = null, string? responseId = null)
        {
            OutputItems = outputItems;
            OutputFormat = outputFormat;
            Messages = messages ?? new List<ModelItem>();
            Id = responseId;
        }
    }
}
