using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using LlmTornado.ChatFunctions;
using LlmTornado.Code;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LlmTornado.Responses;

/// <summary>
/// Whether tool search is executed by the server or by the client.
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum ResponseToolSearchExecution
{
    /// <summary>
    /// OpenAI searches deferred tools declared in the request.
    /// </summary>
    [EnumMember(Value = "server")]
    Server,

    /// <summary>
    /// The model emits a tool search call and the client performs the lookup.
    /// </summary>
    [EnumMember(Value = "client")]
    Client
}

/// <summary>
/// Hosted or client-executed tool search configuration for deferred tools.
/// </summary>
public class ResponseToolSearchTool : ResponseTool
{
    /// <inheritdoc />
    public override string Type => "tool_search";

    /// <summary>
    /// Whether tool search is executed by the server or by the client.
    /// </summary>
    [JsonProperty("execution")]
    public ResponseToolSearchExecution? Execution { get; set; }

    /// <summary>
    /// Description shown to the model for a client-executed tool search tool.
    /// </summary>
    [JsonProperty("description")]
    public string? Description { get; set; }

    /// <summary>
    /// Parameter schema for a client-executed tool search tool.
    /// </summary>
    [JsonProperty("parameters")]
    public JObject? Parameters { get; set; }
}

/// <summary>
/// Groups function or custom tools under a shared namespace for tool search.
/// </summary>
public class ResponseToolNamespace : ResponseTool
{
    /// <inheritdoc />
    public override string Type => "namespace";

    /// <summary>
    /// The namespace name used in tool calls (for example, <c>crm</c>).
    /// </summary>
    [JsonProperty("name", Required = Required.Always)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// A description of the namespace shown to the model.
    /// </summary>
    [JsonProperty("description", Required = Required.Always)]
    public string Description { get; set; } = null!;

    /// <summary>
    /// The function or custom tools available inside this namespace.
    /// </summary>
    [JsonProperty("tools", Required = Required.Always)]
    [JsonConverter(typeof(ResponseNamespaceNestedToolListConverter))]
    public List<ResponseTool> Tools { get; set; } = [];
}

/// <summary>
/// Records a tool search step emitted by the model.
/// </summary>
public class ResponseToolSearchCallItem : IResponseOutputItem, IBuiltInToolCallData
{
    /// <inheritdoc />
    [JsonProperty("type")]
    public string Type { get; set; } = ResponseOutputTypes.ToolSearchCall;

    /// <summary>
    /// The unique ID of the tool search call item.
    /// </summary>
    [JsonProperty("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The unique ID of the tool search call generated by the model.
    /// </summary>
    [JsonProperty("call_id")]
    public string? CallId { get; set; }

    /// <summary>
    /// Arguments used for the tool search call.
    /// </summary>
    [JsonProperty("arguments")]
    public JToken? Arguments { get; set; }

    /// <summary>
    /// Whether tool search was executed by the server or by the client.
    /// </summary>
    [JsonProperty("execution")]
    public ResponseToolSearchExecution Execution { get; set; }

    /// <summary>
    /// The status of the tool search call item.
    /// </summary>
    [JsonProperty("status")]
    public ResponseOutputItemStatus? Status { get; set; }

    /// <summary>
    /// The identifier of the actor that created the item.
    /// </summary>
    [JsonProperty("created_by")]
    public string? CreatedBy { get; set; }
}

/// <summary>
/// Contains the loaded tool definitions returned by tool search.
/// </summary>
public class ResponseToolSearchOutputItem : IResponseOutputItem, IBuiltInToolCallData
{
    /// <inheritdoc />
    [JsonProperty("type")]
    public string Type { get; set; } = ResponseOutputTypes.ToolSearchOutput;

    /// <summary>
    /// The unique ID of the tool search output item.
    /// </summary>
    [JsonProperty("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The unique ID of the tool search call generated by the model.
    /// </summary>
    [JsonProperty("call_id")]
    public string? CallId { get; set; }

    /// <summary>
    /// Whether tool search was executed by the server or by the client.
    /// </summary>
    [JsonProperty("execution")]
    public ResponseToolSearchExecution Execution { get; set; }

    /// <summary>
    /// The status of the tool search output item.
    /// </summary>
    [JsonProperty("status")]
    public ResponseOutputItemStatus? Status { get; set; }

    /// <summary>
    /// The loaded tool definitions returned by tool search.
    /// </summary>
    [JsonProperty("tools")]
    public List<ResponseTool> Tools { get; set; } = [];

    /// <summary>
    /// The identifier of the actor that created the item.
    /// </summary>
    [JsonProperty("created_by")]
    public string? CreatedBy { get; set; }
}

/// <summary>
/// A tool search call item replayed as input for subsequent turns.
/// </summary>
public class ToolSearchCallInput : ResponseInputItem
{
    /// <inheritdoc />
    public override string Type => ResponseOutputTypes.ToolSearchCall;

    /// <summary>
    /// The unique ID of the tool search call item.
    /// </summary>
    [JsonProperty("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The unique ID of the tool search call generated by the model.
    /// </summary>
    [JsonProperty("call_id")]
    public string? CallId { get; set; }

    /// <summary>
    /// Arguments used for the tool search call.
    /// </summary>
    [JsonProperty("arguments")]
    public JToken? Arguments { get; set; }

    /// <summary>
    /// Whether tool search was executed by the server or by the client.
    /// </summary>
    [JsonProperty("execution")]
    public ResponseToolSearchExecution Execution { get; set; }

    /// <summary>
    /// The status of the tool search call item.
    /// </summary>
    [JsonProperty("status")]
    public ResponseMessageStatuses? Status { get; set; }
}

/// <summary>
/// Tool search output returned by the client or replayed from a prior response.
/// </summary>
public class ToolSearchOutputInput : ResponseInputItem
{
    /// <inheritdoc />
    public override string Type => ResponseOutputTypes.ToolSearchOutput;

    /// <summary>
    /// The unique ID of the tool search output item.
    /// </summary>
    [JsonProperty("id")]
    public string? Id { get; set; }

    /// <summary>
    /// The unique ID of the tool search call generated by the model.
    /// </summary>
    [JsonProperty("call_id")]
    public string? CallId { get; set; }

    /// <summary>
    /// Whether tool search was executed by the server or by the client.
    /// </summary>
    [JsonProperty("execution")]
    public ResponseToolSearchExecution Execution { get; set; }

    /// <summary>
    /// The status of the tool search output item.
    /// </summary>
    [JsonProperty("status")]
    public ResponseMessageStatuses? Status { get; set; }

    /// <summary>
    /// The loaded tool definitions returned by tool search.
    /// </summary>
    [JsonProperty("tools")]
    public List<ResponseTool> Tools { get; set; } = [];
}

/// <summary>
/// Serializes nested function/custom tools inside a namespace.
/// </summary>
internal class ResponseNamespaceNestedToolListConverter : JsonConverter<List<ResponseTool>>
{
    public override List<ResponseTool>? ReadJson(JsonReader reader, Type objectType, List<ResponseTool>? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null)
        {
            return null;
        }

        JArray array = JArray.Load(reader);
        List<ResponseTool> result = [];

        foreach (JToken? token in array)
        {
            if (token is not JObject jo)
            {
                continue;
            }

            ResponseTool? tool = jo["type"]?.ToString() switch
            {
                "function" => new ResponseFunctionTool
                {
                    Name = (string)jo["name"]!,
                    Description = (string?)jo["description"],
                    Parameters = jo["parameters"] as JObject,
                    Strict = (bool?)jo["strict"],
                    DeferLoading = (bool?)jo["defer_loading"]
                },
                "custom" => ResponseCustomTool.FromJson(jo),
                _ => null
            };

            if (tool is not null)
            {
                result.Add(tool);
            }
        }

        return result;
    }

    public override void WriteJson(JsonWriter writer, List<ResponseTool>? value, JsonSerializer serializer)
    {
        if (value is null)
        {
            writer.WriteNull();
            return;
        }

        writer.WriteStartArray();
        foreach (ResponseTool tool in value)
        {
            switch (tool)
            {
                case ResponseFunctionTool func:
                    writer.WriteStartObject();
                    writer.WritePropertyName("type");
                    writer.WriteValue(func.Type);
                    writer.WritePropertyName("name");
                    writer.WriteValue(func.Name);
                    if (func.Description is not null)
                    {
                        writer.WritePropertyName("description");
                        writer.WriteValue(func.Description);
                    }
                    if (func.DeferLoading is not null)
                    {
                        writer.WritePropertyName("defer_loading");
                        writer.WriteValue(func.DeferLoading);
                    }
                    if (func.Parameters is not null)
                    {
                        writer.WritePropertyName("parameters");
                        serializer.Serialize(writer, func.Parameters);
                    }
                    if (func.Strict is not null)
                    {
                        writer.WritePropertyName("strict");
                        writer.WriteValue(func.Strict);
                    }
                    writer.WriteEndObject();
                    break;
                case ResponseCustomTool custom:
                    serializer.Serialize(writer, custom);
                    break;
            }
        }
        writer.WriteEndArray();
    }
}
